MONGO_DB_HOST = 'mongo'
MONGO_DB_PORT = 27017

OPENTSDB_HOST = "opentsdb"
OPENTSDB_PORT = 4242

MANAGER_HOST = 'collector'
MANAGER_PORT = 8001

HOST_TOTAL_NUM = 2

CLASSIFY = True
ENABLE_CLASSIFY = "yes"

UPDATE_INTERVAL = "5"